controller_manager:
  ros__parameters:
    update_rate: 30  # Hz
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    acks_cont:
      type: bicycle_steering_controller/BicycleSteeringController


acks_cont:
  ros__parameters:
    publish_rate: 30.0
    wheelbase: 0.2
    front_wheel_radius: 0.03125
    rear_wheel_radius: 0.03125
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ['rear_tracker_joint']
    front_wheels_names: ['front_tracker_joint']
    open_loop: true
    velocity_rolling_window_size: 10
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]
    position_feedback: true
    use_stamped_vel: false

## joint_broad:
##   ros__parameters: