<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name='arm'>

    <xacro:include filename="macros.xacro"/>
    <xacro:property name='box_placement' value='${base_height}'/>

    <xacro:property name='box_length' value='0.05'/>
    <xacro:property name='box_width' value='0.05'/>
    <xacro:property name='box_height' value='0.02'/>

    <xacro:property name='cylinder_length' value='${box_length * 3.5}'/>
    <xacro:property name='cylinder_radius' value='${box_width/3.5}'/>


    <material name='arm1'>
        <color rgba="0.2 0.5 0.3 1.0"/>
    </material>
    <material name='arm2'>
        <color rgba="0.2 1 0.3 1.0"/>
    </material>

    <link name="arm_base">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}"/>
            </geometry>
        </visual>
        <xacro:box_inertia m='0.05' l='${box_length}' w='${box_width}' h='${box_height}' xyz='0.0 0.0 0.0' rpy='0.0 0.0 0.0'/>
        <collision>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}"/>
            </geometry>
        </collision>
        
    </link>

    <joint name="base_armbase" type="fixed">
        <parent link="base_link"/>
        <child link="arm_base"/>
        <origin xyz="0.0 0.0 ${box_placement + box_height/2.0}" rpy="0.0 0.0 0.0"/>
    </joint>
    

    <link name="first_arm_link">
        <visual>
            <origin xyz="0.0 0.0 ${cylinder_length/2.0}" rpy="0.0 0.0 0.0"/>
            <material name="arm1"/>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m='0.1' r='${1.5*cylinder_radius}' h='${1.5*cylinder_length}' xyz='0.0 0.0 0.0' rpy='0.0 0.0 0.0'/>
        
    
    </link>

    <joint name="box_arm_joint" type="revolute">
        <parent link="arm_base"/>
        <child link="first_arm_link"/>
        <axis xyz="0 1 0"/>
        <limit lower="0.0" upper="${pi/2.0}" velocity="50.0" effort="1000.0"/>
        <origin xyz="0 0 ${box_height/2.0}" rpy="0 0 0"/>
    </joint>

    <link name="second_arm_link">
        <visual>
            <origin xyz="0.0 0.0 ${cylinder_length/2.0}" rpy="0.0 0.0 0.0"/>
            <material name="arm2"/>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m='0.1' r='${1.5*cylinder_radius}' h='${1.5*cylinder_length}' xyz='0.0 0.0 0.0' rpy='0.0 0.0 0.0'/>
        
        
    </link>

    <joint name="second_arm_joint" type="revolute">
        <parent link="first_arm_link"/>
        <child link="second_arm_link"/>
        <axis xyz="0 1 0"/>
        <limit lower="0.0" upper="${pi/2.0}" velocity="50.0" effort="1000.0"/>
        <origin xyz="0 0 ${cylinder_length}" rpy="0 0 0"/>
    </joint>
    
</robot>
