<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sensors">

    <!-- properties -->
    <xacro:property name="sensor_length" value="0.015"/>
    <xacro:property name="sensor_width" value="0.015"/>
    <xacro:property name="sensor_height" value="0.015"/>

    <!-- colours materials -->
    <material name="darknavy" ><color rgba="0.0 0.01568627450980392 0.20784313725490197 1.0" /></material>

    <!-- camera sensor  -->
    <link name="camera_sensor">
        <visual>
            <origin xyz="0.0 0.0 ${sensor_height/2.0}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${sensor_length} ${sensor_width} ${sensor_height}"/>
            </geometry>
            <material name="darknavy"/>
        </visual>
        <xacro:box_inertia m='0.25' l='${correction * sensor_length}' w='${correction * sensor_width}' h='${correction * sensor_height}' xyz="0.0 0.0 ${sensor_height/2.0}" rpy="0.0 0.0 0.0"/>
    </link>

    
</robot>