<?xml version="1.0"?>


<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name='self_balance'>
        
                <!-- Variables  -->
    <xacro:property name='base_length' value='0.08'/>
    <xacro:property name='base_width' value='0.16'/>
    <xacro:property name='base_height' value='0.30'/>

    <xacro:property name='wheel_radius' value='${base_length}'/>
    <xacro:property name='wheel_length' value='${base_width / 8.0}'/>


    <material name='green'>
        <color rgba="0.0 0.5 0.0 1.0"/>
    </material>

    <link name="base_foot"></link>
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
        </visual>
    </link>
    <joint name="base_foot" type="fixed">
        <origin xyz="0.0 0.0 ${base_length / 2.0}" rpy="0.0 0.0 0.0"/>
        <parent link="base_foot"/>
        <child link="base_link"/>
    </joint>


    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
    </link>
    
    <joint name="base_right_joint" type="continuous">
        <origin xyz="0.0 ${-base_width /2.0 + -wheel_length/2.0 } ${wheel_radius/2.0}" rpy="1.57 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <axis xyz="0.0 0.0 1"/>
    </joint>


    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
    </link>

    <joint name="base_left_joint" type="continuous">
        <origin xyz="0.0 ${base_width / 2.0 + wheel_length / 2.0} ${wheel_radius/2.0}" rpy="1.57 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <axis xyz="0.0 0.0 1"/>
    </joint>

</robot>