<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="test">

    <!-- Creating Variables -->
    <!-- Base Variables -->
    <xacro:property name='base_length' value='0.4'/>
    <xacro:property name='base_width' value='0.2'/>
    <xacro:property name='base_height' value='0.1'/>

    <!-- Wheels variables -->
    <xacro:property name='wheel_radius' value='${base_length / 8.0}'/>
    <xacro:property name='wheel_length' value='${wheel_radius / 2.0}'/>

    <material name='green'>
        <color rgba="0.0 0.5 0.0 1.0"/>
    </material>

    <!-- base_foot joints -->
    <link name="foot"/>
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
    </link>
    <joint name="base_foot" type="fixed">
        <parent link="foot"/>
        <child link="base_link"/>
        <origin xyz="0.0 0 ${base_height / 2.0}" rpy="0 0.0 0.0"/>
    </joint>

    <!-- left wheel joint -->
    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
    </link>
    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${-base_width / 2.0 + -wheel_length / 2.0} 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
        <axis xyz="0.0 0 1"/>
    </joint>

    <!-- right wheel joint -->
    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
    </link>
    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${base_width / 2.0 + wheel_length / 2.0} 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
        <axis xyz="0.0 0 1"/>
    </joint>

    <!-- front sphere joint -->
    <link name="front_sphere">
        <visual>
            <geometry>  
                <sphere radius="${wheel_radius / 2.0}"/> 
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
    </link>
    <joint name="base_sphere_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_sphere"/>
        <origin xyz="${base_length / 4.0} 0 ${-wheel_radius / 2.0}" rpy="0 0.0 0.0"/>
    </joint>

</robot>
