<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="sensor_radius" value="${wheel_radius/1.7}"/>
  <xacro:property name="sensor_height" value="${wheel_length*1.3}"/>
  <xacro:property name="sensor_radius" value="${wheel_radius/1.7}"/>


  <material name='scan'><color rgba="${255/255} ${108/255} ${10/255} 1.0"/></material>
  
    <link name="base_scan">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <material name="scan"/>
          <geometry>
            <cylinder radius="${sensor_radius}" length="${sensor_height}"/>
          </geometry>
        </visual>
        <xacro:cylinder_inertia m='0.01' r='${correction * sensor_radius}' h='${correction * sensor_height}' xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${sensor_radius}" length="${sensor_height}"/>
          </geometry>
        </collision>
      </link>

      <joint name="base_sensor_joint" type="fixed">
        <origin xyz="${wheel_base/3.0} 0.0 ${base_height + (sensor_height/2.0)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="base_scan"/>
      </joint>
 
      <!-- lidar sensor -->
      <gazebo reference="base_scan">
        <material>Gazebo/Orange</material>
 
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.2</min>
                    <max>8</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>base_scan</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>