<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sensors">

    <!-- properties -->
    <xacro:property name="sensor_length" value="0.015"/>
    <xacro:property name="sensor_width" value="0.015"/>
    <xacro:property name="sensor_height" value="0.015"/>

    <!-- colours materials -->
    <material name="darknavy" ><color rgba="0.0 0.01568627450980392 0.20784313725490197 1.0" /></material>

    <!-- sensor frame  -->
    <link name="base_scan">
        <visual>
            <origin xyz="0.0 0.0 ${sensor_height/2.0}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${sensor_length} ${sensor_width} ${sensor_height}"/>
            </geometry>
            <material name="darknavy"/>
        </visual>
        <xacro:box_inertia m='0.25' l='${correction * sensor_length}' w='${correction * sensor_width}' h='${correction * sensor_height}' xyz="0.0 0.0 ${sensor_height/2.0}" rpy="0.0 0.0 0.0"/>
    </link>

<!-- ultrsonic sensor -->
    <!-- <joint name="sonar_frame_joint" type="fixed">
        <parent link="sensor_frame"/>
        <child link="pico_sonar_0_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
     -->


    <!-- Adding a gazebo sensor -->

    <!-- <gazebo reference='base_scan'>
        <material>Gazebo/Black</material>
        <pose>0 0 0 0 0 0</pose>
        <sensor name="ultrasonic_hc04" type="ray">
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>5</update_rate>
            <ray>
            <scan>
                <horizontal>
                <samples>5</samples>
                <resolution>1.000000</resolution>
                <min_angle>-0.12</min_angle>
                <max_angle>0.12</max_angle>
                </horizontal>
                <vertical>
                <samples>5</samples>
                <resolution>1.000000</resolution>
                <min_angle>-0.01</min_angle>
                <max_angle>0.01</max_angle>
                </vertical>
            </scan>
            <range>
                <min>0.02</min>
                <max>4</max>
                <resolution>0.01</resolution>
            </range>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
            </noise>
            </ray>
            <plugin name="ultrasonic_sensor_hc04" filename="libgazebo_ros_ray_sensor.so">
            <ros>
                <remapping>~/out:=scan</remapping>
            </ros>
            <output_type>sensor_msgs/LaserScan</output_type>
            <radiation_type>ultrasound</radiation_type>
            <frame_name>base_scan</frame_name>
            </plugin>
        </sensor>  
    </gazebo> -->
    
</robot>